// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const SAVE_PERFIL = 'SAVE_PERFIL'
export const SAVE_EXPERIENCIA = 'SAVE_EXPERIENCIA'
export const SAVE_FORMACION = 'SAVE_FORMACION'
export const UPDATE_EXPERIENCIA = 'UPDATE_EXPERIENCIA'
export const UPDATE_FORMACION = 'UPDATE_FORMACION'
export const DELETE_EXPERIENCIA = 'DELETE_EXPERIENCIA'
export const DELETE_FORMACION = 'DELETE_FORMACION'
export const FETCH_EXPERIENCIA = 'FETCH_EXPERIENCIA'
export const FETCH_FORMACION = 'FETCH_FORMACION'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// page.js
export const SET_TITLE = 'SET_TITLE'

// empleo.js
export const SET_SINGLE_VACANTE = 'SET_SINGLE_VACANTE'
export const SET_VACANTES = 'SET_VACANTES'
export const SET_EMPRESA_VACANTES = 'SET_EMPRESA_VACANTES'
export const DELETE_SINGLE_VACANTE = 'DELETE_SINGLE_VACANTE'

// resources.js
export const SET_ESTADOS = 'SET_ESTADOS'
export const SET_MUNICIPIOS = 'SET_MUNICIPIOS'
export const SET_ESTADOS_CIVILES = 'SET_ESTADOS_CIVILES'
export const SET_AREAS_ESPECIALIDAD = 'SET_AREAS_ESPECIALIDAD'
export const SET_PRESTACIONES = 'SET_PRESTACIONES'
